### ISSUE TITLE
Fix: (lint staged) and git pre hooks

### ISSUE THREAD

**Issue by udaypydi** [udaypydi/react-simple-boilerplate#76]
**Describe the bug**
Git pre commit hooks doesn't work as expected.

**To Reproduce**
1. Make code changes
2. git add
3. git commit

**Expected behavior**
Should run tests and lint on the staged  files.

**Comment by udaypydi** [comment]
@mvhk Please have a look at this.

**Comment by mvhk** [comment]
@udaypydi okay

**Comment by mvhk** [comment]
> @mvhk Please have a look at this.

They are working when I checked it now, can you send me a screenshot or  console's logs, that would help me

**Comment by udaypydi** [comment]
Can you attach loom file of what actually is working @mvhk

**Comment by udaypydi** [comment]
@mvhk any updates?

**Comment by mvhk** [comment]
> @mvhk any updates?

Okay, the bug is at `npm run test`, it's trying to run the command like `npm run test foo.jsx` in the pre-commit hook

**Comment by mvhk** [comment]
> @mvhk any updates?
check once ! @udaypydi

**Comment by mvhk** [comment]
> @mvhk any updates?

check once! @udaypydi

**Comment by mvhk** [comment]
fix #85

**Comment by udaypydi** [comment]
Thanks @mvhk
