### ISSUE TITLE
Monolith using lerna

### ISSUE THREAD

**Issue by udaypydi** [udaypydi/react-simple-boilerplate#77]
**Is your feature request related to a problem? Please describe.**
Create a monlith using lerna

**Describe the solution you'd like**
yarn workspaces are good for monlith repos but has complexities in publishing the packages and maintaining versions.

**Describe alternatives you've considered**
yarn workspace was tried earlier. Use lerna.

**Comment by akshay-nm** [comment]
This is done @udaypydi

**Comment by udaypydi** [comment]
Thanks @akshay-nm
