### ISSUE TITLE
Create a CLI with Inquirer

### ISSUE THREAD

**Issue by udaypydi** [udaypydi/react-simple-boilerplate#78]
**Is your feature request related to a problem? Please describe.**
Currently the react simple boilerplate is just a package. Make it an interactive cli tool.

**Describe the solution you'd like**
Use inquirer:
https://www.npmjs.com/package/inquirer

**Describe alternatives you've considered**
yargs was considered earlier.

**Comment by udaypydi** [comment]
@mvhk pls check it out.

**Comment by mvhk** [comment]
> @mvhk pls check it out.

But what are the questions we can ask them? Is there an option to choose in our template between any? 
I mean like, for now, there is no multiple options : eg: Redux/recoil?

**Comment by mvhk** [comment]
@udaypydi open can you open this issue, I'm working on it...
